project_id = "upxsbhsamorhvnfebvor"

[auth]
enabled = true
external_providers = []
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = false
enable_confirmations = false

[auth.phone]
enable_signup = false
enable_confirmations = false

[database]
enabled = true

[api]
enabled = true
port = 54321

[db]
port = 54322

[studio]
enabled = true
port = 54323

[functions.upload-webinar-logo]
verify_jwt = false

[functions.generate-coupon]
verify_jwt = false