-- Sales Pipeline dashboard table (mirrors the LeadList Attended/Unattended sheet).
-- Run this once in the Supabase SQL editor.

CREATE TABLE IF NOT EXISTS public.pipeline_leads (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  tab TEXT NOT NULL DEFAULT 'attended',          -- 'attended' | 'unattended'
  sl_no INTEGER,
  client TEXT,
  industry TEXT,
  requirement TEXT,
  estimated_value TEXT,
  current_stage TEXT,
  next_step TEXT,
  expected_closure TEXT,
  technical_notes TEXT,
  business TEXT,
  status TEXT,
  email TEXT,
  phone TEXT,
  description TEXT
);

CREATE INDEX IF NOT EXISTS idx_pipeline_leads_tab ON public.pipeline_leads (tab);
CREATE INDEX IF NOT EXISTS idx_pipeline_leads_created_at ON public.pipeline_leads (created_at DESC);

ALTER TABLE public.pipeline_leads ENABLE ROW LEVEL SECURITY;

-- The dashboard is behind an app-level login. These policies let the app read
-- and manage rows with the anon key (same posture as the existing lead tables).
CREATE POLICY "pipeline read"   ON public.pipeline_leads FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "pipeline insert" ON public.pipeline_leads FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "pipeline update" ON public.pipeline_leads FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "pipeline delete" ON public.pipeline_leads FOR DELETE TO anon, authenticated USING (true);

-- Seed: current leads from the sheet (run once).
INSERT INTO public.pipeline_leads
  (tab, sl_no, client, industry, requirement, estimated_value, current_stage, next_step, expected_closure, technical_notes, business, status, email, phone)
VALUES
  ('attended', 1, 'Concast', 'Machinaries import export', 'Automate the end-to-end data preparation process for the CEO Dashboard by eliminating manual data collection, copy-paste, validation, and report refresh activities. The solution should automatically collect data from SAP reports, bank statements, stock registers, RDC files, sales registers, and ME2L exports, transform and validate the data, consolidate it into a centralized master dataset, refresh the existing CEO Excel dashboard without changing its formulas or analytical views, and notify stakeholders once the dashboard is ready. The solution must be deployed on-premises, preserve the current reporting workflow, and provide accurate, timely, and auditable business reports with minimal manual intervention.', '15,00,000', 'closing stage', 'sent followup mesage on july 6th', '10/07/2026', NULL, NULL, NULL, 'nilesh.vaghela@primetals.com', NULL),
  ('attended', 2, 'Lets Unbound', 'Education & EdTech', 'AI Agentic Automation & Business Process Orchestration for an EdTech company. Scope includes building an AI orchestration layer across existing systems (Zoho CRM, WATI, Microsoft Teams, Classcard, Edison OS, Razorpay & Beehiiv) to automate end-to-end Sales, Operations, Academic and Management workflows. Modules include AI proposal intelligence, lead prioritization, AI follow-up engine, voice reminders, attendance monitoring, invoice & renewal automation, AI student performance summaries, executive dashboards, cross-platform integrations, and a dedicated AI Operations Success Program for continuous optimization and support.', NULL, 'initial stage', 'proposal sent ; client is not ok with the budget', NULL, NULL, NULL, NULL, NULL, '88050 08840'),
  ('attended', 3, 'Asif', 'Plastic and toys manufacturing', 'Manufacturing company with two businesses: (1) Plastic injection molding & plastic pipe manufacturing (father''s company) supplying OEMs and internal toy business, (2) Toy manufacturing (Airsoft Toys) assembling plastic parts and supplying OEMs. Current operations use Busy Accounting, Excel, WhatsApp, and manual planning. Requirements include AI-based Purchase Order automation, automatic BOM & raw material calculation, inventory planning, shortage detection, procurement & vendor automation, RFQ generation, vendor comparison, PO automation, dispatch & ETA tracking, production planning, machine utilization optimization, machine scheduling, live production monitoring, rejection & quality analytics, inventory aging, daily/weekly/monthly P&L dashboards, employee performance analytics, WhatsApp alerts, management dashboards, and complete integration with Busy ERP to reduce manual planning and improve operational efficiency.', '30,00,000', 'initial stage', 'proposal sent; once client responds we can proceed on next step', NULL, NULL, NULL, NULL, NULL, '95990 29378'),
  ('attended', 4, 'Krishna prasad', 'Dairy day', 'Enterprise AI Meeting Intelligence Platform (Hybrid Deployment) – Develop a production-ready AI meeting assistant for Microsoft Teams, Zoom, and Google Meet using Recall AI for automated meeting joining, recording, speaker diarization, and speech-to-text. Generate AI-powered Minutes of Meeting (MoM), executive summaries, action items, key decisions, risks, follow-ups, and email summaries using OpenAI. Build role-based dashboards (Admin, Executive, Director), meeting history, search, analytics, and reporting. Support hybrid deployment (On-Premise + Azure), RBAC, Azure AD/SSO integration, NAS storage, configurable retention policies, secure enterprise architecture, audit logs, and scalable infrastructure. Initial deployment for 5–10 executive users with future expansion to approximately 85 senior management users, including installation, training, and production deployment.', '9,00,000', 'initial stage', 'proposal sent , no response for calls, messages and mail, sending followup mail daily', NULL, NULL, NULL, NULL, NULL, '97432 46815'),
  ('attended', 5, 'Azhar khan', 'L & D (Learning and development', 'Design and implement an AI Revenue Workforce using Agentic AI Orchestration to automate the client''s end-to-end revenue operations. The solution should continuously monitor business news for market opportunities, automatically research target companies, identify relevant decision-makers, qualify leads based on predefined ICP criteria, generate founder-style personalized outreach emails, manage CRM updates, automate follow-up sequences, and provide a real-time executive dashboard with pipeline visibility. The objective is to reduce repetitive manual work, increase sales productivity, improve lead quality, accelerate outreach and follow-ups, and enable the existing team to focus on high-value activities such as relationship building, consultative selling, and closing deals, while maintaining human approval for critical customer communications.', NULL, 'initial stage', 'no resposne ; sending followups', NULL, NULL, NULL, NULL, NULL, '98928 05838'),
  ('attended', 6, 'Akash', 'E commerce', 'Client operates a cosmetics and perfume distribution business that has been running for approximately 3.5 years and works with around 35 vendors. The company imports products from suppliers and distributes them through an established offline B2B network while using Tally for accounting, inventory, sales, and purchase management. The founder currently manages all customer communication manually, including product enquiries, stock availability, pricing, discounts, offers, and order confirmations, resulting in significant time consumption and limiting business scalability. The client is also facing issues with overbooking fast-moving SKUs because orders are confirmed without validating real-time inventory, while inventory planning is done manually by analysing previous sales data in Tally, leading to only partially accurate demand forecasting. The immediate requirement is to develop an AI-powered WhatsApp Sales Assistant capable of answering customer queries, searching products and SKUs, sharing product catalogues with images, providing pricing, discounts, stock availability, product recommendations, FAQs, order enquiries, and supporting seamless human handoff for complex or bulk order conversations through a configurable hybrid AI-human workflow. Additionally, the client requires an Inventory Analytics and Forecasting Dashboard integrated with Tally to analyse daily, weekly, and monthly sales trends, identify fast-moving and slow-moving products, forecast future demand, recommend reorder quantities, monitor inventory health, generate stock alerts, assist in purchase planning, and provide business intelligence dashboards for better decision-making. In future phases, the client plans to implement a fully customized CRM/ERP system including Customer Management, Vendor Management, Product Management, Purchase Orders, Sales Orders, Inventory Management, Invoice Generation, Payment Tracking, WhatsApp and Email Notifications, Workflow Automation, Reporting, Analytics, User Roles, and AI-driven business insights. The overall objective is to reduce founder dependency, automate repetitive customer interactions, prevent inventory overbooking, improve operational efficiency, enhance customer response time, and build a scalable digital infrastructure that supports long-term business growth.', NULL, 'initial stage', 'proposal sent ; client is not ok with the budget', NULL, NULL, NULL, NULL, NULL, '832 956 6438'),
  ('attended', 7, 'Arun', 'multiple business', 'Client operates multiple businesses including Real Estate, Interior Solutions, Trading, and Manufacturing in Dubai. Primary requirement is to build an AI-powered lead generation and business growth platform starting with Real Estate and Interior businesses. The solution should use AI to research the target market, identify ICPs, create and optimize Meta and Google Ads campaigns, generate qualified leads, automatically qualify prospects based on budget, location and requirements, capture all enquiries into a centralized CRM, automate WhatsApp and email follow-ups, schedule appointments, provide sales pipeline management, marketing analytics and founder dashboard, with the long-term vision of connecting all business verticals into one unified platform for centralized operations and business growth.', NULL, 'initial stage', NULL, NULL, NULL, NULL, NULL, NULL, '971585190071'),
  ('attended', 9, 'Nidhi', 'wedding gift', 'Wedding gifting manufacturing company with 30+ years of experience seeking an AI-driven business process automation and workflow management system. Currently operates with 18 employees (previously 80) and has no CRM or centralized software. Facing major challenges in task management, employee accountability, communication gaps, lack of process implementation, and owner dependency for daily operations. Employees often forget tasks, updates are not recorded, and previous task trackers and inventory systems failed due to poor adoption. The owner wants a mandatory process-driven system where employees must complete required fields before moving to the next stage, ensuring SOP compliance, accountability, and visibility. Required solution includes CRM, task management, workflow automation, employee performance tracking, approval workflows, dashboards, inventory management, notifications, AI-generated reports, and analytics to monitor operations, reduce manual supervision, improve communication, prevent revenue leakage, and enable the owner to focus on business growth instead of operational management.', NULL, NULL, 'Nidhi is expecting site visit 
So Viaan should go there and talk to her manager on the requirement 
So this will help to build closer connection with client', NULL, NULL, NULL, NULL, NULL, '9810033857'),
  ('attended', 10, 'Zarana', 'Kalavid Branding and advertising agency', 'Kalavid is looking to build a customized end-to-end Agency Operations Management System (not a standard CRM) to automate and streamline their complete project execution workflow. The system should manage the entire lifecycle from lead/project creation, coordinator assignment, designer/editor allocation, visualizer assignment, workload balancing, priority management, deadline tracking, task distribution, creative brief sharing, file management, internal reviews, client approvals, correction cycles, final delivery, invoicing, payment tracking, and reporting. They require workload-based automatic task allocation, real-time dashboards for management, coordinators, designers, editors, and visualizers, reminders for deadlines and pending approvals, centralized document and version management, WhatsApp integration where feasible, project-wise communication tracking, role-based access, approval workflows, time tracking, analytics, and management reports. The solution should be fully customized to match Kalavid''s existing operational process, be easy for their 90+ member team to adopt, and serve as a scalable operational platform that improves visibility, collaboration, efficiency, and project execution while reducing manual coordination.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '9316484085'),
  ('unattended', 1, 'Sudhakar', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'PDF sent', 'Bestqualityeducation.com', '971555437845'),
  ('unattended', 2, 'veekay', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'manufacturer of artificial leather, pcv coated fabric anc allied products', 'PDF sent', 'https://www.veekaytexcoat.in/', '9311070706'),
  ('unattended', 3, 'shrey', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'HR', 'Follow up message sent', NULL, '9999710081'),
  ('unattended', 4, 'vishnuvardhan', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'cracker business , needa call and whatsapp automation', 'Follow up message sent', NULL, '8056749264'),
  ('unattended', 5, 'vallalarasu', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'social media marketing and lead capture', 'Follow up message sent', NULL, '9600035510'),
  ('unattended', 6, 'Abhilasha', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'outsourcing book keeping , 100 employees', 'Follow up message sent', NULL, '7567311224'),
  ('unattended', 7, 'sourabh', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'edtech , 70 employees', 'Follow up message sent', NULL, '7018301132'),
  ('unattended', 8, 'loan doctor', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'finance/loan service/business consultant', 'Follow up message sent', NULL, '9499799598');
