-- Sync all Cold Outreach — 12 Month step copy from app templates.
-- Generated by scripts/generate-cold-outreach-copy-sql.mjs — re-run after copy edits.
-- Safe to re-run. Skips steps with metadata.copy_locked = true.

DO $sync$
DECLARE
  seq_id UUID;
  updated_count INT := 0;
BEGIN
  SELECT id INTO seq_id FROM public.em_sequences WHERE name = 'Cold Outreach — 12 Month' LIMIT 1;
  IF seq_id IS NULL THEN
    RAISE NOTICE 'Sequence "Cold Outreach — 12 Month" not found — run seed migration first.';
    RETURN;
  END IF;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 0,
    delay_hours = 0,
    condition = E'always',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'Manual follow-up at {{company}}?',
    body_template = E'Most teams lose leads not from bad marketing, but slow response.
We fix that without ripping out what {{company}} already uses.
Reply if that''s worth a look.',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 1
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = 1,
    delay_days = 3,
    delay_hours = 0,
    condition = E'opened_not_replied',
    step_type = E'case_study',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'Saw you opened — quick example',
    body_template = E'Since you opened the last one — here''s the short version.
We helped a team cut lead response time by 80%, without adding headcount.
{{case_study_url}}',
    case_study_mode = E'fixed',
    case_study_slug = E'lead-capture-qualification',
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 2
    AND branch_lane = E'opened'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = 1,
    delay_days = 3,
    delay_hours = 0,
    condition = E'no_open',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'Re: quick question',
    body_template = E'Might''ve gotten buried — happy to share how teams like {{company}} stopped losing leads to slow follow-up.
Tell me if it''s not useful and I''ll stop here.',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 2
    AND branch_lane = E'not_opened'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 5,
    delay_hours = 0,
    condition = E'no_reply',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'A number worth checking',
    body_template = E'Most teams don''t track this, but slow lead response usually costs 20–30% of pipeline, quietly.
Worth 15 minutes to see where that number sits for {{company}}?',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 3
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = 3,
    delay_days = 3,
    delay_hours = 0,
    condition = E'opened_not_replied',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'Worth 15 min, {{name}}?',
    body_template = E'Since you''ve read a couple of these — happy to walk through a quick automation audit for {{company}}, no pitch deck involved.
Reply with a time that works.',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 4
    AND branch_lane = E'opened'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = 3,
    delay_days = 3,
    delay_hours = 0,
    condition = E'no_open',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'Different angle',
    body_template = E'Trying this from another direction: most teams we talk to lose hours a week to manual lead handling.
If that sounds like {{company}}, worth a short call.',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 4
    AND branch_lane = E'not_opened'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'no_reply',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'Should I close your file?',
    body_template = E'I''ve sent a few of these without a reply, so I''ll assume the timing''s off.
If that changes, or automation becomes a priority for {{company}}, just reply — I''ll pick it back up.',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 5
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'no_meeting',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'Free 15 min, {{name}}?',
    body_template = E'No pitch here — just a slot if you want it: {{calendly_url}}
If automation for {{company}} isn''t a priority right now, no worries, I''ll stop pinging.',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 6
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 3,
    delay_hours = 0,
    condition = E'clicked',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'Saw you opened this — one question',
    body_template = E'No pressure, just curious if this is something {{company}} is actively looking at, or just filed for later.',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 7
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'no_reply',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'Free 15 min, {{name}}?',
    body_template = E'No pitch here — just a slot if you want it: {{calendly_url}}
If automation for {{company}} isn''t a priority right now, no worries, I''ll stop pinging.',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 8
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'opened_not_replied',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'Saw you opened this — one question',
    body_template = E'No pressure, just curious if this is something {{company}} is actively looking at, or just filed for later.',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 9
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'no_reply',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'Where the ROI actually shows up',
    body_template = E'Most teams expect automation ROI in "saved time." The bigger number is usually recovered leads that were falling through cracks.
Worth a quick look at where that applies to {{company}}.',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 10
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'no_reply',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'Still manual on {{company}}''s follow-up?',
    body_template = E'Curious if this is still handled by hand at {{company}}, or if something''s already in place.',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 11
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'no_reply',
    step_type = E'case_study',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'Lead response in under a minute',
    body_template = E'A team similar to {{company}} used to lose leads sitting in an inbox for hours.
Now the first response goes out in under a minute, automatically.
{{case_study_url}}',
    case_study_mode = E'fixed',
    case_study_slug = E'lead-capture-qualification',
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 12
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'no_reply',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'Free automation audit for {{company}}?',
    body_template = E'No cost, no obligation — I''ll point out one or two things {{company}} could automate this month. Interested?',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 13
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'no_reply',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'What manual follow-up is costing {{company}}',
    body_template = E'Most teams don''t track this, but slow lead follow-up usually costs 20-30% of pipeline, quietly.
Happy to walk through where that''s likely leaking for {{company}} — 15 min, your call: {{calendly_url}}',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 14
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'opened_not_replied',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'~12 hrs/week, roughly',
    body_template = E'That''s the average time teams like {{company}} were losing to manual lead handling before automating it.
If that number''s in the right ballpark for you, worth a look.',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 15
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'no_reply',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'Compliance load creeping up?',
    body_template = E'If reporting or audit trail requirements have gotten heavier this year, that''s usually a sign manual processes are about to break.
Automating that layer tends to fix both problems at once.',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 16
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'no_reply',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'Rough estimate — how many hours/week?',
    body_template = E'No wrong answer, just curious what manual follow-up is costing your team weekly right now.',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 17
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'no_reply',
    step_type = E'case_study',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'Staffing workflow we automated',
    body_template = E'A staffing firm was manually matching candidates to job orders — hours of repetitive work every week.
We automated the matching and cut that down to minutes.
{{case_study_url}}',
    case_study_mode = E'fixed',
    case_study_slug = E'internal-workflow-automation',
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 18
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'no_reply',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'My guess at {{company}}''s biggest fix',
    body_template = E'Based on companies your size, I''d guess lead follow-up is the first thing worth automating. Want me to confirm or correct that guess?',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 19
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'no_reply',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'A few teams in your space already did this',
    body_template = E'Not naming names, but a couple of companies doing similar work to {{company}} automated their lead intake this year and stopped losing leads overnight.
Want the rundown? {{calendly_url}}',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 20
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'opened_not_replied',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'Guessing where {{company}}''s stuck',
    body_template = E'If I had to guess, it''s either lead response time or data entry between tools. Usually one of the two.
Which one''s closer?',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 21
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'no_reply',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'Not trying to create urgency, but',
    body_template = E'A handful of companies in your space have quietly automated core workflows this year. Not a trend piece — just what''s actually happening.',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 22
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'no_reply',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'What''s the actual bottleneck?',
    body_template = E'If you had to name one thing slowing {{company}} down operationally, what would it be?',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 23
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'no_reply',
    step_type = E'case_study',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'Compliance workflow for a finance team',
    body_template = E'A fintech team was manually compiling data for compliance reporting each cycle.
We automated the document processing — same reporting, a fraction of the manual work.
{{case_study_url}}',
    case_study_mode = E'fixed',
    case_study_slug = E'document-data-processing',
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 24
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'no_reply',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'15 minutes, nothing needed from you',
    body_template = E'The audit''s free and doesn''t require prep on your end — just a look at what''s already happening at {{company}}.',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 25
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'no_reply',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'One question about {{company}}''s follow-up',
    body_template = E'When a lead comes in at {{company}}, how long before someone actually responds?
If the honest answer is "depends," that''s usually fixable in a week.',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 26
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'opened_not_replied',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'A quiet win for a team like yours',
    body_template = E'A similar-sized company cut their lead response time from hours to minutes without adding headcount.
Can share exactly how if useful.',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 27
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'no_reply',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'Scaling {{company}} without scaling headcount',
    body_template = E'If growth plans for {{company}} assume hiring to keep up with volume, automation is usually the cheaper first move.',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 28
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'no_reply',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'How many tools are you stitching together?',
    body_template = E'Most teams have 3-4 tools that don''t talk to each other, and someone''s manually bridging the gap. Sound familiar?',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 29
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'no_reply',
    step_type = E'case_study',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'Patient intake without the backlog',
    body_template = E'Manual intake was creating a backlog before appointments even started.
An automated intake flow cleared that bottleneck without adding staff.
{{case_study_url}}',
    case_study_mode = E'fixed',
    case_study_slug = E'ai-customer-support',
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 30
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'no_reply',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'What you''d walk away with',
    body_template = E'Not a sales pitch — you''d get a short list of what to automate first at {{company}}, ranked by impact. Yours either way.',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 31
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'no_reply',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'Reshab here — one more try',
    body_template = E'I''ve sent a few of these and don''t want to keep cluttering your inbox.
If there''s any interest in fixing manual follow-up at {{company}}, reply and I''ll keep it short. If not, I''ll close this out.',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 32
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'opened_not_replied',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'Timing shift in your industry',
    body_template = E'Buyers are expecting faster responses than they were even a year ago — the bar''s moved, quietly.
Might be worth checking if {{company}}''s process kept up.',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 33
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'no_reply',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'What your customers actually notice',
    body_template = E'Customers don''t see your backend — they just notice when responses are fast. That''s usually the real value of automating this.',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 34
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'no_reply',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'Is this blocking growth plans?',
    body_template = E'Sometimes the manual process isn''t just annoying — it''s actually capping how fast {{company}} can scale. Worth checking which one it is.',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 35
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'no_reply',
    step_type = E'case_study',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'Order support on autopilot',
    body_template = E'An e-commerce team was drowning in repetitive order-status questions.
Automating first-response support freed their team for the tickets that actually need a human.
{{case_study_url}}',
    case_study_mode = E'fixed',
    case_study_slug = E'ai-customer-support',
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 36
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'no_reply',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'Standing offer, no deadline',
    body_template = E'This isn''t going anywhere and there''s no pressure — just let me know whenever it''s useful to look at {{company}}''s process.',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 37
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'no_reply',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'Planning season at {{company}}?',
    body_template = E'If you''re mapping out next quarter, this is usually when automation gets budgeted and then forgotten by Q2.
Worth 15 min now while it''s on the radar? {{calendly_url}}',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 38
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'opened_not_replied',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'10 minutes, no pitch',
    body_template = E'Not a sales call — just a look at where {{company}}''s current process has gaps, free either way.',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 39
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'no_reply',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'Data you''re probably not capturing',
    body_template = E'Manual processes usually mean no clean record of what happened with a lead. Automating it tends to surface that data for the first time.',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 40
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'no_reply',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'What''s your team saying about this?',
    body_template = E'Usually the people doing the manual work complain about it long before leadership hears it. Has that started at {{company}}?',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 41
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'no_reply',
    step_type = E'case_study',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'Manufacturing ops, less manual handoff',
    body_template = E'A manufacturing team had multiple manual handoffs between ops and scheduling.
Automating that handoff cut delays and errors in one move.
{{case_study_url}}',
    case_study_mode = E'fixed',
    case_study_slug = E'internal-workflow-automation',
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 42
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'no_reply',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'How {{company}} compares',
    body_template = E'Curious how automated your process is versus others in your space? The audit usually answers that pretty quickly.',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 43
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'no_reply',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'"Too much to switch right now" — fair',
    body_template = E'Most teams assume automation means ripping out their current stack. It doesn''t — this usually plugs into what {{company}} already uses.
If that''s what''s held this up, worth a quick call to see the actual lift.',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 44
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'opened_not_replied',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'Manual vs. automated, in one line',
    body_template = E'Manual: lead sits for hours, maybe gets a reply. Automated: lead gets a response in under a minute, every time.
That''s really the whole pitch.',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 45
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'no_reply',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'Speed-to-lead, the actual number',
    body_template = E'Response time inside 5 minutes converts significantly better than anything slower — most teams don''t realize how far off they are until they check.',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 46
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'no_reply',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'Do you know your lead drop-off rate?',
    body_template = E'Most companies don''t track how many leads go cold from slow follow-up — until they automate and see the number.',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 47
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'no_reply',
    step_type = E'case_study',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'Lead to tour without the lag',
    body_template = E'A real estate team was manually scheduling tours after every lead came in — hours of back-and-forth.
Automated scheduling closed that gap same-day, consistently.
{{case_study_url}}',
    case_study_mode = E'fixed',
    case_study_slug = E'crm-sales-pipeline-automation',
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 48
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'no_reply',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'No call required, if you''d rather not',
    body_template = E'If a call feels like overkill, reply here and I''ll just send over what I''d flag for {{company}} directly.',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 49
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'no_reply',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'Your competitors aren''t waiting',
    body_template = E'The teams winning right now in your space aren''t doing anything smarter — they''re just not doing it manually anymore.
Happy to show you what that looks like for {{company}}: {{calendly_url}}',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 50
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'opened_not_replied',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'Still relevant, or should I stop?',
    body_template = E'Genuinely asking — if this isn''t useful for {{company}} right now, tell me and I''ll take you off the list. If it is, happy to keep going.',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 51
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'no_reply',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'What''s changed for {{company}} this year',
    body_template = E'Worth a quick gut-check: is {{company}}''s process handling the same volume it was a year ago, or has it quietly gotten harder to keep up?',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 52
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'no_reply',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'Still a priority?',
    body_template = E'Just checking in — is fixing this still on your radar for {{company}}, or has it moved down the list?',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 53
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'no_reply',
    step_type = E'case_study',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'The workflow that performed best',
    body_template = E'Out of everything we''ve automated this year, one workflow consistently gets the fastest results: lead response time.
Here''s what that actually looked like.
{{case_study_url}}',
    case_study_mode = E'fixed',
    case_study_slug = E'lead-capture-qualification',
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 54
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  UPDATE public.em_sequence_steps SET
    branch_after_step_order = NULL,
    delay_days = 7,
    delay_hours = 0,
    condition = E'no_reply',
    step_type = E'template',
    ai_angle = NULL,
    ai_instructions = NULL,
    subject_template = E'Last one on this — audit''s still open',
    body_template = E'Closing this thread out soon. If a free look at {{company}}''s automation gaps is still useful, this is the easy way in.',
    case_study_mode = E'fixed',
    case_study_slug = NULL,
    ai_generated = false
  WHERE sequence_id = seq_id
    AND step_order = 55
    AND branch_lane = E'main'
    AND COALESCE((metadata->>'copy_locked')::boolean, false) = false;

  GET DIAGNOSTICS updated_count = ROW_COUNT;

  DELETE FROM public.em_ai_draft_cache
  WHERE step_id IN (
    SELECT id FROM public.em_sequence_steps
    WHERE sequence_id = seq_id
      AND step_order BETWEEN 1 AND 55
      AND COALESCE((metadata->>'copy_locked')::boolean, false) = false
  );

  -- Optional: default empty calendly_url setting for {{calendly_url}} merge var
  INSERT INTO public.em_settings (key, value)
  VALUES ('calendly_url', '""'::jsonb)
  ON CONFLICT (key) DO NOTHING;

  RAISE NOTICE 'Cold outreach copy sync complete for sequence %', seq_id;
END $sync$;
